/*
 * Regenerates assets/seed.js - the offline bootstrap the page falls back to
 * when it is opened straight from disk with no server behind it.
 *
 * Only settings, packages and stock accounts are copied. Orders are never
 * baked into the page; they come from the server.
 *
 *   node tools/make-seed.js [source.json]
 *
 * Default source is data/shop_data.json.
 */
const fs = require('fs');
const path = require('path');

const root = path.join(__dirname, '..');
const src = process.argv[2] || path.join(root, 'data', 'shop_data.json');

const raw = JSON.parse(fs.readFileSync(src, 'utf8'));
const doc = raw && raw.data ? raw.data : raw;

const seed = {
  settings: doc.settings || {},
  packages: doc.packages || [],
  stockAccounts: doc.stockAccounts || [],
  salesLogs: [],
  deletedOrders: []
};

const out =
  '/* Generated by tools/make-seed.js - do not edit by hand.\n' +
  ' * Offline bootstrap only: prices, staff and mail accounts, never orders.\n' +
  ' * Regenerate with:  node tools/make-seed.js\n' +
  ' */\n' +
  'window.SEED_DATA = ' + JSON.stringify(seed, null, 2) + ';\n';

fs.mkdirSync(path.join(root, 'assets'), { recursive: true });
fs.writeFileSync(path.join(root, 'assets', 'seed.js'), out, 'utf8');

console.log('seed.js written from ' + path.relative(root, src));
console.log('  packages: ' + seed.packages.length +
  ', stock accounts: ' + seed.stockAccounts.length +
  ', staff: ' + ((seed.settings.employees || []).length));
